on: [workflow_call]
jobs:
  audit:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Audit Code
        run: pnpm audit
