on:
  workflow_call:
    inputs:
      dry-run:
        required: true
        type: boolean
permissions:
  contents: read # for checkout
jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Release
        run: |
          if [ "${{ inputs.dry-run }}" == 'true' ]; then
            DRY_RUN_OPTION="--dry-run --branches ${{ github.ref_name }}"
          else
            DRY_RUN_OPTION=""
          fi
          pnpm exec semantic-release ${DRY_RUN_OPTION}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
